<?php


namespace App\Services;

use App\Contracts\Admin;
use App\Contracts\User;
use App\Data\CreateAdminData;
use App\Data\CreateUserData;
use App\Models\User as ModelsUser;
use App\Repository\UserRepository;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Facades\Hash;
use Nette\Utils\Random;
use PhpParser\Node\Expr\AssignOp\Mod;

class AdminServices implements Admin
{
    public function __construct(
        protected UserRepository $userRepository
    )
    {}

    public function createUser(CreateUserData $data): ModelsUser
    {
        $usuario= $this->userRepository->createUser($data);
        $usuario->assignRole('Web-Team-default-Member');
        return $usuario;
    }

    public function createAdmin(CreateAdminData $data): ModelsUser
    {   $passwordAutoGenerated=Random::generate(8);
        $userData=CreateUserData::from([
            "name"       =>    $data->name,
            "last_name"  =>    $data->last_name,
            "email"      =>    $data->email,
            "password"   =>    (env("APP_ENV")=="production")?Hash::make($passwordAutoGenerated):Hash::make(env("PASWORD_ADMIN_DEFAULT")),
        ]);
        $usuario= $this->userRepository->createUser($userData);
        $usuario->assignRole('Web-Team-default-Member');
        return $usuario;
    }

    public function consultUserByEmail(string $email): ?ModelsUser
    {
        return $this->userRepository->consultUserByEmail($email);
    }

    public function consultUserById(int $id): ?ModelsUser
    {
        return $this->userRepository->consultUserById($id);
    }

    public function consultAll(): Collection
    {
        return $this->userRepository->consultAll();
    }

    public function deleteById(int $id): void
    {
        $this->userRepository->deleteUser($id);
    }

    public function getFiltredUsers(array $filters): Collection
    {
        return $this->userRepository->getFiltredUsers($filters);
    }

    public function getFiltredUsersPaginated(array $filters, int $perPage = 15): LengthAwarePaginator
    {
        return $this->userRepository->getFiltredUsersPaginated($filters,$perPage);
    }

    public function actualizarRoles(int $id, array $roles): void
    {
        $this->userRepository->actualizarRoles($id,$roles);
    }


}


?>
